app = "ochattinho-bot"
primary_region = "gru"  # SÃ£o Paulo

[build]

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  cpus = 1
  cpu_kind = "shared"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
