[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt", "mkdir -p /usr/local/bin", "ln -sf $(which ffmpeg) /usr/local/bin/ffmpeg"]

[env]
PATH = "/usr/local/bin:$PATH"